language: python
python: 3.5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

env:
  - TOX_ENV=py27
  - TOX_ENV=py35

install:
- pip install tox

script:
    CXX="g++-4.9" CC="gcc-4.9" tox -e $TOX_ENV
